apiVersion: v1
kind: Namespace
metadata:
  name:  backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custody-backend
  labels:
    tipo: backend_comun
    app: custody-backend
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tipo: backend_comun
      app: custody-backend
  template:
    metadata:
      labels:
        tipo: backend_comun
        app: custody-backend
    spec:
      containers:
        - name: custody-api
          image: custody-api:latest
          imagePullPolicy: Never
          env:
          - name: dsn
            value: "host=psql-backend.backend port=5432 user=postgres password=postgres dbname=lab sslmode=disable"
          - name: port
            value: "5000"
          resources:
            requests:
              memory: "20Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: custody-backend
  namespace: backend
  labels:
    tipo: backend_comun
    app: custody-backend
spec:
  ports:
    - name: custody
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    tipo: backend_comun
    app: custody-backend
  type: ClusterIP