name: Platform CI

on:
  push:
    tags:
    - "*"

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - name: test tag
        id: build-image
        run: |
           echo "ok push tag"