name: Platform CI

on:
  push:
    branches:
    - test

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy

    steps:
    
      steps:
      - name: test push
        id: build-image
        run: |
           echo "ok push test"