name: Platform CI

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - name: test push
        id: build-image
        run: |
           echo "ok publish release"